
export const CORE_IDS = {
    Type: "0",
    Title: "1",
    DOI: "2",
    URL: "3",
    "First name": "4",
    "Last name": "5",
    Year: "6",
    "Month of year": "7",
    "Day of month": "8",
    "Hour of day": "9",
    "Minute of hour": "10",
    "Seconds of minute": "11",
    "Nanoseconds": "12",
    "Timezone": "13",

    Author: "p0",
    Authors: "p1",
    Group: "p2",
    "Author(s) or Group": "p3",
    Date: "p4",
    "Short date": "p5",
    Document: "p6",
}
